AllCops:
  TargetRubyVersion: 2.7

  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
  Exclude:
    - 'vendor/**/*'
    - 'stubs/**/*'
    - 'spec/support/shared_contexts/*'

  NewCops: enable

########################################
# Style Cops

# Checks formatting of special comments
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

########################################
# Lint Cops

Lint/SuppressedException:
  Enabled: false

########################################
# Security Cops

Security/Eval:
  Enabled: false

########################################
# Metrics Cops

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 30

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

########################################
# Metrics Cops

Naming/FileName:
  Enabled: false

########################################
# Layout Cops

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Max: 110
